# PostgreSQL
[postgres]
DB = "app_db_pg_local"
HOST = "localhost"
PORT = 5432
DRIVER = "psycopg"

# SQLAlchemy
[sqla]
ECHO = false
ECHO_POOL = false
POOL_SIZE = 30
MAX_OVERFLOW = 20

# Logs
[logs]
# Can be set to "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
LEVEL = "DEBUG"
